import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

/**
 * Guards on the generated dossier.
 *
 * The dossier is what the agent will say about a real person, so the failure
 * that matters is not "the build crashed" — it is "the build succeeded and
 * produced something subtly wrong". These assertions are aimed at the silent
 * cases: a section that extracted to nothing, a claim that should not be there,
 * and the specific extraction bug that shipped a mangled label.
 */
const dossier = readFileSync(fileURLToPath(new URL('../../data/dossier.md', import.meta.url)), 'utf8')

describe('dossier', () => {
  it('produces a dossier with all seven projects and a non-trivial length', () => {
    for (const p of ['Recto', 'AskSheet', 'Critiq', 'RAG Lab', 'GraphRead', 'PlaneMode', 'Concierge']) {
      expect(dossier).toContain(p)
    }
    expect(dossier.length).toBeGreaterThan(2000)
  })

  it('records how it was generated and what fed it', () => {
    expect(dossier).toContain('<!-- generated by build-dossier -->')
    expect(dossier).toContain('src/components/islands/ExperienceTimeline.tsx')
    expect(dossier).toContain('scripts/build-dossier.ts')
  })

  /**
   * Derived from the timeline rather than hard-coded against it.
   *
   * This assertion used to list the roles as literals, which meant a CV update
   * failed the test for the correct reason with a misleading message: the
   * dossier was right and the test was stale. Reading the same source the
   * generator reads makes the test answer the question it is actually asking —
   * did every job in the timeline survive extraction — and keeps it true the
   * next time the CV changes.
   */
  it('carries every employer and role from the timeline', () => {
    const timeline = readFileSync(
      fileURLToPath(new URL('../islands/ExperienceTimeline.tsx', import.meta.url)),
      'utf8',
    )
    const jobs = timeline.slice(
      timeline.indexOf('const jobs: Job[] ='),
      timeline.indexOf('];', timeline.indexOf('const jobs: Job[] =')),
    )

    const roles = [...jobs.matchAll(/role:\s*'([^']+)'/g)].map((m) => m[1])
    const companies = [...jobs.matchAll(/company:\s*'([^']+)'/g)].map((m) => m[1])

    // If the extraction above breaks, every loop below passes vacuously — which
    // is precisely the silent success this file exists to prevent.
    expect(roles.length).toBeGreaterThanOrEqual(4)
    expect(companies.length).toBe(roles.length)

    for (const company of new Set(companies)) expect(dossier).toContain(company)
    for (const role of new Set(roles)) expect(dossier).toContain(role)
  })

  it('does not present the in-build projects as shipped', () => {
    expect(dossier).toContain('not shipped products')
    // The seven do not exist yet. An agent offering to link to them would be
    // sending people to 404s.
    expect(dossier).toMatch(/do not (describe|offer)/i)
  })

  it('tells the agent to speak in the third person', () => {
    expect(dossier).toMatch(/third person/i)
  })

  it('gives the agent somewhere to send questions it cannot answer', () => {
    expect(dossier).toContain('abdulrahmanmahmutoglu@gmail.com')
  })

  it('has no runaway labels from a backtracking extractor', () => {
    // Regression guard. The highlight-card extractor once backtracked past the
    // `<strong>` tags in the About prose and emitted an entire paragraph as a
    // bullet label. It looked plausible in a diff and was wrong.
    const labels = [...dossier.matchAll(/^- \*\*(.+?):\*\*/gm)].map((m) => m[1])
    expect(labels.length).toBeGreaterThan(5)
    for (const label of labels) {
      expect(label.length, `runaway label: ${label.slice(0, 80)}…`).toBeLessThan(40)
    }
  })

  it('leaves no unresolved markup or entities in the prose', () => {
    expect(dossier).not.toMatch(/<\/?(div|span|strong|p|h[1-6])\b/)
    expect(dossier).not.toContain('&nbsp;')
    expect(dossier).not.toContain('&amp;')
  })
})
