import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

/**
 * Guards on the generated dossier.
 *
 * The dossier is what the agent will say about a real person, so the failure
 * that matters is not "the build crashed" — it is "the build succeeded and
 * produced something subtly wrong". These assertions are aimed at the silent
 * cases: a section that extracted to nothing, a claim that should not be there,
 * and the specific extraction bug that shipped a mangled label.
 */
const dossier = readFileSync(fileURLToPath(new URL('../../data/dossier.md', import.meta.url)), 'utf8')

describe('dossier', () => {
  it('produces a dossier with all seven projects and a non-trivial length', () => {
    for (const p of ['Recto', 'AskSheet', 'Critiq', 'RAG Lab', 'GraphRead', 'PlaneMode', 'Concierge']) {
      expect(dossier).toContain(p)
    }
    expect(dossier.length).toBeGreaterThan(2000)
  })

  it('records how it was generated and what fed it', () => {
    expect(dossier).toContain('<!-- generated by build-dossier -->')
    expect(dossier).toContain('src/components/islands/ExperienceTimeline.tsx')
    expect(dossier).toContain('scripts/build-dossier.ts')
  })

  it('carries every employer and role from the timeline', () => {
    for (const company of ['Cybernetic Labs', 'Megaventory', 'OptimumTek']) {
      expect(dossier).toContain(company)
    }
    for (const role of [
      'Senior Frontend Engineer',
      'Frontend Engineer',
      'Web Developer (Erasmus+)',
      'Frontend Developer',
    ]) {
      expect(dossier).toContain(role)
    }
  })

  it('does not present the in-build projects as shipped', () => {
    expect(dossier).toContain('not shipped products')
    // The seven do not exist yet. An agent offering to link to them would be
    // sending people to 404s.
    expect(dossier).toMatch(/do not (describe|offer)/i)
  })

  it('tells the agent to speak in the third person', () => {
    expect(dossier).toMatch(/third person/i)
  })

  it('gives the agent somewhere to send questions it cannot answer', () => {
    expect(dossier).toContain('abdulrahmanmahmutoglu@gmail.com')
  })

  it('has no runaway labels from a backtracking extractor', () => {
    // Regression guard. The highlight-card extractor once backtracked past the
    // `<strong>` tags in the About prose and emitted an entire paragraph as a
    // bullet label. It looked plausible in a diff and was wrong.
    const labels = [...dossier.matchAll(/^- \*\*(.+?):\*\*/gm)].map((m) => m[1])
    expect(labels.length).toBeGreaterThan(5)
    for (const label of labels) {
      expect(label.length, `runaway label: ${label.slice(0, 80)}…`).toBeLessThan(40)
    }
  })

  it('leaves no unresolved markup or entities in the prose', () => {
    expect(dossier).not.toMatch(/<\/?(div|span|strong|p|h[1-6])\b/)
    expect(dossier).not.toContain('&nbsp;')
    expect(dossier).not.toContain('&amp;')
  })
})
