- name: Nuxt to Github Pages
  # You may pin to the exact commit or the version.
  # uses: ashkantaravati/NuxtToGithubPages@1d3040411fc2d234b6907434dc8560100171e3fb
  uses: ashkantaravati/NuxtToGithubPages@v1.0
  with:
    # Your username
    username: AbdAsh
    # Your reponame
    reponame: abdash.github.io
    # Your Github token
    token: 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
    # Your git commit email
    gitemail: abdash2011@gmail.com
    # Your git commit name
    gitname: # optional, default is CI
    # Your git commit message
    gitmsg: # optional, default is deploy
    # Your custom domain
    cname: abdash.info
